demo/config/routes.rb
Rails.application.routes.draw do
  resources :personas

end

demo/app/models/persona.rb
class Persona < ActiveRecord::Base
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :tlf)
    end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/personas_helper.rb
module PersonasHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tlf %><br>
    <%= f.number_field :tlf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

demo/app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

demo/app/views/personas/index.html.erb
<h1>Listing personas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tlf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.nombre %></td>
        <td><%= persona.tlf %></td>
        <td><%= link_to 'Show', persona %></td>
        <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
        <td><%= link_to 'Destroy', persona, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Persona', new_persona_path %>

demo/app/views/personas/new.html.erb
<h1>New persona</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

demo/app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Tlf:</strong>
  <%= @persona.tlf %>
</p>

<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>